version: "3"
services:
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - /home/vxndr/code/pets/budget_bot/docker/Postgresql
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: vxndr
        POSTGRES_PASSWORD: vxndr
        POSTGRES_DB: budget_bot
